language: node_js
node_js: 10
install:
  - npm install
script: 
  - npm test
addons:
  chrome: stable
before_install:
  - google_chrome_stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"